name: test1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.0.0"

dependencies:

  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  permission_handler: ^11.4.0
  intl: ^0.20.2
  share_plus: ^10.1.4
  device_info_plus: ^9.1.2
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
